- name: Add neo4j repository key
  shell: |
    wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
    echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
    sudo apt-get update

- name: Install neo4j
  apt:
    name: neo4j
    state: latest
    update_cache: yes
