# install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure
- name: setting neo4j
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '#dbms.default_listen_address=0.0.0.0'
    line: "dbms.default_listen_address=0.0.0.0"
    state: present
  when: neo4j_version != "3.5"
    
- name: setting neo4j
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '#dbms.connector.bolt.listen_address=:7687'
    line: "dbms.connector.bolt.listen_address=0.0.0.0:7687"
    state: present
  when: neo4j_version == "3.5"
      
- name: restart neo4j
  service: name=neo4j state=restarted enabled=yes
  
- block: 
  - name: Copy init_password
    template:
      src: neo4j.sh
      dest: /data/config/neo4j.sh

  - name: Execute init password
    shell: bash /data/config/neo4j.sh
  when: neo4j_version != "3.5"

# print version
- block:
  - name: Check Neo4j Version
    shell: sudo sh -c "neo4j version 1>> /data/logs/install_version.txt"
