neo4j_repo_meta:
  "3.5":
     Debian: "3.5"
  "4.0":
     Debian: "4.0"
  "4.1":
     Debian: "4.1"

neo4j_version_meta:
  "3.5":
     RedHat: "3.5.*"
  "4.0":
     RedHat: "4.0.*"
  "4.1":
     RedHat: "4.1.*"
